#include "samples:shaders/sources/common/common_inc.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(binding = 0, rg32f) uniform writeonly image2D OutputMoments;

uniform sampler2DArray InputMoments;
uniform int ShadowIndex;
uniform float Sigma;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 bounds = imageSize(OutputMoments).xy;

    // Skip unnecessary shader calls
    if (pixel.x >= bounds.x || pixel.y >= bounds.y)
        return;

    // Clamp radius
    float sigma = max(Sigma, 0.01);
    // ~99.7% Gaussian лежит внутри ±3 sigma
    int radius = min(int(ceil(3.0 * sigma)), LITE3D_VSM_BLUR_MAX_RADIUS);
    
    vec2 result = vec2(0.0);
    float weightSum = 0.0;

    for (int i = -radius; i <= radius; ++i)
    {
        float w = Gaussian(float(i), sigma);

        ivec2 offset = ivec2(1, 0) * i;  // Horizontal offset
        ivec2 samplePixel = clamp(pixel + offset, ivec2(0), bounds.xy - ivec2(1));

        // use texelFetch to optimize performance, linear filtering sampling is too heavy
        result += texelFetch(InputMoments, ivec3(samplePixel, ShadowIndex), 0).rg * w;
        weightSum += w;
    }

    result /= weightSum;

    imageStore(OutputMoments, pixel, vec4(result, 0.0, 0.0));
}
