#include "samples:shaders/sources/common/common_inc.glsl"

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(binding = 0, rg32f) uniform writeonly image2DArray OutputMoments;

layout(std140) uniform ShadowIndex
{
    ivec4 shadowIndex[LITE3D_SHADOW_CACHE_MAX_COUNT / 4 + 1];
};

uniform sampler2DArray InputMoments;
uniform int Mode;
uniform float Sigma;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    int layerIndex = int(gl_GlobalInvocationID.z)+1; // skip zero index because it is size
    const ivec2 bounds = imageSize(OutputMoments).xy;

    // Skip unnecessary shader calls
    if (pixel.x >= bounds.x || pixel.y >= bounds.y)
        return;

    int layer = shadowIndex[layerIndex/4][int(mod(layerIndex, 4))];
    vec2 texelSize = 1.0 / vec2(bounds.xy);
    vec2 uv = (vec2(pixel) + 0.5) * texelSize;

    // Clamp radius
    float sigma = max(Sigma, 0.01);
    // ~99.7% Gaussian лежит внутри ±3 sigma
    int radius = min(int(ceil(3.0 * sigma)), LITE3D_VSM_BLUR_MAX_RADIUS);
    
    vec2 result = vec2(0.0);
    float weightSum = 0.0;

    for (int i = -radius; i <= radius; ++i)
    {
        float fi = float(i);
        float w = Gaussian(fi, sigma);
        vec2 offset = (Mode == 0 ? vec2(1.0, 0.0) : vec2(0.0, 1.0)) * texelSize * fi;

        result += textureLod(InputMoments, vec3(uv + offset, layer), 0.0).rg * w;
        weightSum += w;
    }

    result /= weightSum;

    imageStore(OutputMoments, ivec3(pixel, layer), vec4(result, 0.0, 0.0));
}
