version: '1.0.{build}'

image: 
  - Visual Studio 2022
  - Ubuntu

hosts:
  localhost: 127.0.0.1
  
configuration:
  - Release
  
init:
  - sh: mkdir -p /home/appveyor/builds/lite3d_linux
  - cmd: mkdir C:\builds\lite3d_win
  
install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y libdevil-dev libassimp-dev libsdl2-dev libfreetype6-dev libbullet-dev
  
before_build:
  - sh: cd /home/appveyor/builds/lite3d_linux
  - sh: cmake -DCMAKE_BUILD_TYPE=Release /home/appveyor/projects/3dlite
  - cmd: cd C:\builds\lite3d_win
  - cmd: cmake -DCMAKE_BUILD_TYPE=Release C:\projects\3dlite

build:
  project: C:\builds\lite3d_win\lite3d.sln
  
for:
-
  matrix:
    only:
      - image: Ubuntu

  build_script:
  - sh: make all
