version: '1.0.7.{build}'

image: 
  - Visual Studio 2022
  - Ubuntu

hosts:
  localhost: 127.0.0.1
  
configuration:
  - Debug
# - Release

platform:
  - x64

environment:
  matrix:
    - GL_PROVIDER: GLEW
    - GL_PROVIDER: GLES2
    - GL_PROVIDER: GLES3
  
init:
  - sh: mkdir -p /home/appveyor/builds/lite3d_linux
  - cmd: mkdir C:\builds\lite3d_win
  
install:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y libdevil-dev libassimp-dev libsdl2-dev libfreetype6-dev libbullet-dev
  
before_build:
  - cmd: cd C:\builds\lite3d_win
  - cmd: cmake -A x64 -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DENABLE_METRICS=ON C:\projects\3dlite

build:
  project: C:\builds\lite3d_win\lite3d.sln
  
for:
- matrix:
    exclude:
      - image: Visual Studio 2022
        GL_PROVIDER: GLES2
      - image: Visual Studio 2022
        GL_PROVIDER: GLES3

- matrix:
    only:
      - image: Ubuntu

  before_build:
    - sh: cd /home/appveyor/builds/lite3d_linux
    - sh: cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION -DGRAPHIC_BACKEND=$GL_PROVIDER -DENABLE_METRICS=ON /home/appveyor/projects/3dlite -Wno-dev

  build_script:
  - sh: make all
